urls:
  ccodes: "https://raw.githubusercontent.com/lukes/ISO-3166-Countries-with-Regional-Codes/master/all/all.csv"
  stations: "https://raw.githubusercontent.com/trainline-eu/stations/master/stations.csv"

proj:
  crs_def: "epsg:4326"
  crs_eur: "epsg:3035"

logger:
  format: "%(asctime)s - %(name)-20s - %(funcName)-20s - %(levelname)-20s: %(message)s"
